[package]
name = "rfc793"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun-tap = "0.1.4"
dotenv = "0.15.0"
etherparse = "0.15.0"
